### ISSUE TITLE
can't detect infinite loop 

### ISSUE THREAD

**Issue by kumarmukul133** [scriptnull/compilex#6]
Sir please look into this matter asap!!!
When i run an infinite loop..then in c and cpp it doesn't give any output.
And in java it simply says--> error:""

**Comment by scriptnull** [comment]
Hi,
  Thanks for reporting. Sorry that, I have been busy lately to respond back. I just now deprecated this package. Please read the [deprecation notice](https://github.com/scriptnull/compilex#deprecation-notice) for alternate solutions.

But,  I think, the whole "detection of inifinte loop" feature should have been designed as timeout feature. After getting timeout as argument, we would typically stop the execution if the program takes longer than the timeout specified.

Anyways ! Thanks.
